# Generated by Django 3.1.2 on 2021-03-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_post_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_updated']},
        ),
    ]
